require("anandxs.options")
require("anandxs.keymap")
require("anandxs.plugins")
require("anandxs.colorscheme")
require("anandxs.cmp")
require("anandxs.lsp")
require("anandxs.telescope")
require("anandxs.treesitter")
